class TokpedPage < SitePrism::Page
    set_url '/'
  
    element :username, '#user-name'
    element :password, '#password'
    element :btn_login, '#login-button'
    element :title, '.title'
    elements :dropdown_sort, '.product_sort_container option'
    elements :item_name, '.inventory_item_name'
    elements :item_price, '.inventory_item_price'
    element :item_name_detail, '.inventory_details_name.large_size'
    element :item_price_detail, 'div.inventory_details_price'
    element :btn_add_to_cart, '.btn.btn_primary.btn_small.btn_inventory'
    element :btn_remove_cart, '.btn.btn_secondary.btn_small.btn_inventory'
    element :btn_open_cart, '#shopping_cart_container'
    element :btn_checkout, '#checkout'
    element :first_name, '#first-name'
    element :last_name, '#last-name'
    element :zip_code, '#postal-code'
    element :btn_continue, '#continue'
    elements :payment_shipping_info, '.summary_value_label'
    element :subtotal, '.summary_subtotal_label'
    element :tax, '.summary_tax_label'
    element :total, '.summary_total_label'
    element :btn_finish, '#finish'
    element :header_order, '.complete-header'
    element :text_order, '.complete-text'
    element :btn_back_to_home, '#back-to-products'
  end
  